# This file is a template, and might need editing before it works on your project.
# Template project: https://gitlab.com/pages/jekyll
# Docs: https://docs.gitlab.com/ce/pages/
image: ruby:2.3

variables:
  JEKYLL_ENV: production

before_script:
- bundle install

test:
  stage: test
  script:
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master

cloudflare:
  stage: deploy
  script:
  - sleep 15s
  - curl -X POST "https://api.cloudflare.com/client/v4/zones/c15c1715ee61d6169e818565692a8e3bpurge_cache" -H "X-Auth-Email: $CLOUDFLARE_API_USER" -H "X-Auth-Key: $CLOUDFLARE_API_TOKEN" -H "Content-Type: application/json" --data '{"purge_everything":true}'
